### ISSUE TITLE
ISSUE: migration is not loaded and ran

### ISSUE THREAD

**Issue by curunoir** [robertogallea/LaravelMetrics#2]
Hello,

after installing the package with composer require on an existing Laravel 6 project, I launched 'php artisan migrate' and I was suprised to have nothing migrated.

After digging into the ServiceProvider code I found that the migration maybe should have been copied into the project migrations directory but that didn't happened.

As the documentation don't mention it what is the correct path to have the migration of the metrics table ?

**Comment by robertogallea** [comment]
Hi,
you have to publish migrations, I forgot to mention it in the readme, sorry.
```
php artisan vendor:publish --provider=robertogallea\\LaravelMetrics\\MetricsServiceProvider --tag=migrations
```
