### ISSUE TITLE
ISSUE: Class 'Str' not found when storing meters

### ISSUE THREAD

**Issue by curunoir** [robertogallea/LaravelMetrics#3]
Hello,

I just tried to test the documentation example after mannually created the metrics table migration with this code : 

```
        $marker = Metrics::meter('metric-name');

        $marker->mark();
```
There is an error 'Class 'Str' not found' launched in the line with code : 

vendor/robertogallea/laravel-metrics/src/Models/Meter.php:33

`        return \Str::kebab(class_basename($this));`

**Comment by robertogallea** [comment]
What package and Laravel versions are you using?

**Comment by curunoir** [comment]
Here are the dependencies I'm using on the project

    "require": {
        "php": "^7.2",
        "arcanedev/log-viewer": "5.*",
        "barryvdh/laravel-dompdf": "^0.8.6",
        "darkaonline/l5-swagger": "6.*",
        "fico7489/laravel-pivot": "^3.0",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.5",
        "iatstuti/laravel-cascade-soft-deletes": "^2.0",
        "intervention/image": "^2.5",
        "jenssegers/date": "^3.5",
        "laravel/framework": "6.*",
        "laravel/helpers": "^1.2",
        "laravel/meta": "^3.1",
        "laravel/passport": "^8.4",
        "laravel/tinker": "^2.0",
        "laravelcollective/html": "^6.1",
        "lastguest/murmurhash": "^2.0",
        "league/csv": "^9.5",
        "league/flysystem": "^1.0",
        "linfo/linfo": "^4.0",
        "maatwebsite/excel": "^3.1",
        "phpseclib/phpseclib": "^2.0",
        "predis/predis": "^1.1",
        "rap2hpoutre/fast-excel": "^1.7",
        "rollbar/rollbar-laravel": "^6.0",
        "spatie/regex": "^1.4",
        "swaggest/json-schema": "^0.12.28",
        "symfony/expression-language": "^5.0",
        "symfony/process": "^4.4",
        "vinkla/hashids": "7.*",
        "webpatser/laravel-uuid": "^3.0",
        "yajra/laravel-datatables-oracle": "^9.9"
    }

**Comment by robertogallea** [comment]
Do you have `Str` facade registered on `config/app.php`?

```
  'aliases' => 
        ...
        'Str' => Illuminate\Support\Str::class,
```

**Comment by curunoir** [comment]
No I have not. It is not really a required registration on every project. If the package have a strong dependency on this registration maybe it should registers it itself ?

**Comment by robertogallea** [comment]
I don't know if register it be the Service Provider would be better, but I
choose not to register it, since, although not required, it is registered
by default on every Laravel project.

Il mar 18 ago 2020, 10:45 curunoir <notifications@github.com> ha scritto:

**Comment by curunoir** [comment]
To be honest I think the cleanest way would be to have the full namespace on the use lines :)

`use Illuminate\Support\Str;`

Because you can't assume that every project will have the default facades remaining and also because there might be collisions problems with over classes : local Str class, Psy\Util\Str, Spatie\Regex\Helpers\Str

**Comment by robertogallea** [comment]
This is a perfectly reasonable idea. If you have time please submit a PR,
otherwise I will make one myself.

Please let me know if you find the package useful. It will need some more
testing for sure. And more functionalities as well.

Thanks

**Comment by curunoir** [comment]
I think the package is really interesting and pretty well designed, and there was not much alternatives for the need of storing metrics. I'm happy that you answer so quickly because I wasn't sure that the package was still in development.

I'm also considering the projects/forks laravel-prometheus-exporter which might fit my needs. I'm not really sure that I need to persist all the metrics I want in my project in database, maybe store them in Redis and expose them as prometheus exporters is enough for me.

Maybe both packages could be usefull together, using yours to create, compute some metrics easily and exposes them in what they call a "Collector" which is an abstract way to expose metrics.

I have never did a PR on an open source project but I will give a try. Thanks for the answers. :)
